version: '3.8'
services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '25565:25565'
    environment:
      - MC_VERSION=1.21.4
      - MC_MEMORY=2048M
      - EULA=TRUE
      - PORT=25565
    container_name: minecraft-paper
    volumes:
      - ./data:/app/data
    stdin_open: true
    tty: true
    restart: unless-stopped
